<div class="text_block">
    <p>The following terms and conditions (the "Terms of Use") are mandatory rules for all users and visitors (individually or collectively "Users") of Videouri website. All Videouri Users must signify their agreement to these Terms of Use, Videouri's Privacy, found at http://mediatram.com/content/privacy, and Videouri's DMCA Policy, found at http://videouri.com/legal/dmca. In case you don't agree to these Terms of Use, Videouri's Privacy, or Videouri's DMCA Policy, please do not use our service.</p>
    <p>Videouri support team may notify you when these Terms of Use will change, however you should review the most recent version at http://videouri.com/legal/terms from time to time. Videouri reserves the right to modify these Terms of Use at any time, and all Users must signify their agreement to such changes to use this service in the future.</p>
    <p>Third-party websites and services linked by Videouri have their own Terms of Use which cannot be controlled by us. Note that Videouri does not host and has no control over the content that can be accessed using third-party services as well. If you find your own video using Videouri and believe that it is being accessible in a abusive way and constitutes your copyright infringement, please contact our support team using these <a href="http://videouri.com/legal/dmca_policy">instructions</a>.</p>
    <p>Videouri offers its search technology on an "as is" basis. By using Videouri services you agree to take all possible risks. Videouri does not make any warranties about the accuracy, reliability and usefulness or completeness of its search results. Note that some of the materials identified and located with Videouri may be not copyright-free or error-free. Videouri's search generates automatic results which may lead to unexpected or undesirable references. These references may contain offensive, obscene, or illegal information.</p>
    <p>Videouri services are not intended for children under 13. In case you are under 13 years of age, then please do not use Videouri. Ask your parents for advice and they will help you to find lots of other great websites which are appropriate for you.</p>

    <?php if (! $alex = false): ?>
    <p>Videouri is a trademark of Videouri Corporation. The information from this website and its databases may not be used, copied, distributed, performed, sublicensed, modified, rented, altered, reverse engineered or recompiled in any way without written permission of its owner. All other trademarks are the property of their respective owners.</p>
    <?php endif; ?>
</div>